[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Serial Monitor Settings ---
monitor_speed = 921600
monitor_port = COM9
monitor_filters = esp32_exception_decoder

; --- Hardware Configuration ---
board_build.flash_mode = dio
board_build.arduino.memory_type = qio_qspi
board_build.partitions = default.csv

; --- Build Flags ---
build_flags = 
    ; Enables the internal USB CDC (Serial over USB)
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Optional: Define your I2C pins here if you want them global
    -D I2C_SDA=8
    -D I2C_SCL=9

; --- Library Dependencies ---
lib_deps = 
    bogde/HX711 @ ^0.7.5